### PR TITLE
Interface specs update

### PR DESCRIPTION
**Pull request by grasph**
- Removed the Algebra part
- Changed spatial_mag2 to rho2 after discussion with Uwe
- Add more explanation on the coordinate system support
- Fix some typos

### CODE REVIEW

**Comment by grasph** [comment]
merging in order to generate the doc. We can update it later.

**Comment by Moelf** [comment]
We should have doc preview setup

**Comment by szabo137** [comment]
I would also propose, that we require at least one approval before merging into main.

**Comment by oschulz** [comment]
I would add that Lorentz vectors be subtypes of `AbstractLorentzVector` to the requirements.

**Comment by Moelf** [comment]
>I would add that Lorentz vectors be subtypes of AbstractLorentzVector to the requirements.

that seems to defeat the purpose of using the current interface pattern.

and for practical purpose, because Julia does not have multiple sub-typing, it would be quite restrictive in practice.

**Comment by szabo137** [comment]
As we discussed offline, the general kinematic interface does not need a common super type to be flexible. However, there will be a restricted group of types called _Lorentz vectors_ which subtype from a common `AbstractLorentzVector`. These types implement the kinematic interface already present _and_ the vector space arithmetics (implemented by the provider as an interface function). 

With that we have a clear separation of things that have kinematic properties, and Lorentz vectors also supporting arithmetics. 

Add to the todo: 
- [ ] Reflect this in the docs
- [ ] Rewrite the current description of the kinematic interface avoiding the usage of `LorentzVector` (I already started with this)
- [ ] Find a better name for _object that has kinematic information`

**Comment by oschulz** [comment]
I thought we had kinda agreed that we will have an `AbstractLorentzVector` supertype (which also shouldn't be restrictive, because "being a Lorentz vector" should be the primary property of any Lorentz vector implementation , so there wouldn't be a problem with lack of multiple inheritance). That doesn't apply to things that have a Lorentz vector, instead of being a Lorentz vector, of course.

**Comment by szabo137** [comment]
@oschulz i guess this is reflected by my proposal, isn't it?

**Comment by oschulz** [comment]
> @oschulz I guess this is reflected by my proposal, isn't it?

Yes, sorry,  I was catching up on GitHub emails and overlooked your post. :-)

**Pull request merged**
